### PR TITLE
add support for using tsnet to connect to tailscale 

### PR DESCRIPTION
**Pull request by willnorris**
This adds support for specifying a Tailscale auth key in the user's Corefile. When provided, that key is used to have coredns join the tailnet directly, rather than relying on having tailscale installed on the local system. This simplifies deployment since everything needed is compiled into the coredns binary, and allows Tailscale ACLs to be applied to coredns specifically, independent of the hosting system.

Note that this is built on top of #53 (good bug number for a DNS project! 😛 ), so really the second commit is the one that matters here.  The biggest downside of this change is the number of additional dependencies it brings along, but that's because it's including an entire Tailscale daemon in library form.

### CODE REVIEW

**Comment by damomurf** [comment]
@willnorris As with #53: if it’s not too much to ask, could you rebase this from the main branch? I’ve merged a number of vulnerability fixes, version bumps and some earlier new functionality PRs?

**Comment by willnorris** [comment]
No problem, done.  As before, this is written on top of #53, so only the second commit is new.  (I really wish GitHub supported chained PRs 😞 )

**Comment by willnorris** [comment]
I also ended up restructuring the Corefile parsing logic a tiny bit.  It's the same as what I had in the original version of this PR, and is based on the pattern that coredns seems to use in the official plugins.

**Comment by spudlymurf** [comment]
@willnorris Apologies, but I think this needs another rebase onto main and then we can merge asap. I'll then push a new release. 👍

**Comment by willnorris** [comment]
hah!  It looks like I had already rebased my local client after you merged #53, but forgot to push :)  Should hopefully be good now.

**Comment by spudlymurf** [comment]
Awesome, thanks @willnorris. 👍

**Pull request merged**
